// Generate a large flat gate-level netlist (standard-cell style) for the
// scalability demo: a pipelined datapath with S register stages and limited
// logic depth per stage, which is what synthesized netlists look like.
import { writeFileSync } from 'node:fs';

const N = parseInt(process.argv[2] ?? '1500', 10);
const OUT = process.argv[3] ?? 'src/examples/gates.v';
const STAGES = parseInt(process.argv[4] ?? '6', 10);
const MAX_DEPTH = 6;

let seed = 0x2545f491;
const rnd = () => {
  seed ^= seed << 13; seed >>>= 0;
  seed ^= seed >>> 17;
  seed ^= seed << 5; seed >>>= 0;
  return (seed >>> 0) / 4294967296;
};
const pick = (arr) => arr[Math.floor(rnd() * arr.length)];

const cells = [
  { name: 'NAND2_X1', ins: ['A1', 'A2'], out: 'ZN', w: 4 },
  { name: 'NOR2_X1', ins: ['A1', 'A2'], out: 'ZN', w: 3 },
  { name: 'AND2_X1', ins: ['A1', 'A2'], out: 'Z', w: 3 },
  { name: 'OR2_X1', ins: ['A1', 'A2'], out: 'Z', w: 2 },
  { name: 'XOR2_X1', ins: ['A', 'B'], out: 'Z', w: 2 },
  { name: 'XNOR2_X1', ins: ['A', 'B'], out: 'ZN', w: 1 },
  { name: 'INV_X1', ins: ['A'], out: 'ZN', w: 4 },
  { name: 'BUF_X2', ins: ['A'], out: 'Z', w: 1 },
  { name: 'NAND3_X1', ins: ['A1', 'A2', 'A3'], out: 'ZN', w: 2 },
  { name: 'AOI21_X1', ins: ['A', 'B1', 'B2'], out: 'ZN', w: 2 },
  { name: 'OAI21_X1', ins: ['A', 'B1', 'B2'], out: 'ZN', w: 2 },
  { name: 'MUX2_X1', ins: ['I0', 'I1', 'S'], out: 'Z', w: 2 },
];
const weighted = cells.flatMap((c) => Array(c.w).fill(c));

const nIn = 32;
const nOut = 16;
const flopsPerStage = Math.max(8, Math.round((N * 0.2) / STAGES));
const combPerStage = Math.round((N - flopsPerStage * STAGES - nOut - STAGES) / STAGES);

const lines = [];
lines.push('// Flat gate-level netlist generated by scripts/gen-gates.mjs');
lines.push(`// ~${N} cells: ${STAGES} pipeline stages x (${combPerStage} gates + ${flopsPerStage} flops), ${nIn} inputs, ${nOut} outputs`);
lines.push('module gatelevel_top (');
lines.push('  input  wire clk,');
lines.push('  input  wire rst_n,');
lines.push('  input  wire en,');
lines.push(`  input  wire [${nIn - 1}:0] din,`);
lines.push(`  output wire [${nOut - 1}:0] dout`);
lines.push(');');

let cellIdx = 0;
let netIdx = 0;
let prevStageOutputs = [];
for (let i = 0; i < nIn; i++) prevStageOutputs.push({ name: `din[${i}]`, depth: 0 });
let lastComb = [];
for (let s = 0; s < STAGES; s++) {
  lines.push(`  // ---- stage ${s}`);
  const comb = [];
  for (let i = 0; i < combPerStage; i++) {
    const c = pick(weighted);
    const out = `n${netIdx++}`;
    lines.push(`  wire ${out};`);
    // inputs: previous stage outputs or shallow cells of this stage (limits logic depth)
    const shallow = comb.filter((x) => x.depth < MAX_DEPTH);
    const ins = c.ins.map(() => {
      const fromPrev = rnd() < 0.35 || shallow.length < 4;
      return fromPrev ? pick(prevStageOutputs) : pick(shallow.slice(Math.max(0, shallow.length - 60)));
    });
    const depth = Math.max(...ins.map((x) => x.depth)) + 1;
    const conns = c.ins.map((p, k) => `.${p}(${ins[k].name})`).join(', ');
    lines.push(`  ${c.name} U${cellIdx++} (${conns}, .${c.out}(${out}));`);
    comb.push({ name: out, depth });
  }
  // per-stage enable (high fan-out net -> drawn as labels)
  lines.push(`  wire en_${s};`);
  lines.push(`  AND2_X1 U${cellIdx++} (.A1(en), .A2(${pick(comb).name}), .Z(en_${s}));`);
  const q = [];
  const deep = comb.filter((x) => x.depth >= 3);
  for (let i = 0; i < flopsPerStage; i++) {
    const d = pick(deep.length ? deep : comb);
    const name = `q${s}_${i}`;
    lines.push(`  wire ${name};`);
    if (rnd() < 0.25) lines.push(`  EDFFR_X1 U${cellIdx++} (.CK(clk), .RN(rst_n), .E(en_${s}), .D(${d.name}), .Q(${name}));`);
    else lines.push(`  DFFR_X1 U${cellIdx++} (.CK(clk), .RN(rst_n), .D(${d.name}), .Q(${name}));`);
    q.push({ name, depth: 0 });
  }
  prevStageOutputs = q;
  lastComb = comb;
}
for (let i = 0; i < nOut; i++) {
  const src = i % 2 ? pick(lastComb).name : pick(prevStageOutputs).name;
  lines.push(`  BUF_X4 U${cellIdx++} (.A(${src}), .Z(dout[${i}]));`);
}
lines.push('endmodule');
writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`wrote ${OUT}: ${cellIdx} cells`);
